# Generated by Django 4.1 on 2022-10-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hujra1', ''), ('hujra2', 'Шоймардонов Элмурод'), ('hujra3', 'Махмудзода Илхо'), ('hujra4', 'Давлатзода Киёмиддин'), ('hujra5', 'Амиргулхоноава Н.'), ('hujra6', 'Назаров Рамазон'), ('hujra7', 'Восидиён Фарход'), ('hujra8', 'Фархуддинов Фаррух'), ('hujra9', 'Аброри Шукухидди'), ('hujra10', 'Файзуллозода Фаррух'), ('hujra11', 'Нагзибекова Сохибсултон '), ('hujra12', 'Химатова Гулчахон'), ('hujra13', 'Мухаббатова Соима'), ('hujra14', 'Кабирова М'), ('hujra15', 'Ризоев Халил'), ('hujra16', 'Каримова Раъно'), ('hujra17', 'Мирзохомидзода Хусноро'), ('hujra18', 'Маллаева Чаррос'), ('hujra19', 'Июрохимова Назокат'), ('hujra20', 'Гадоева Гуландон'), ('hujra21', 'Солиев Фаррух'), ('hujra22', 'Леонов Валерий '), ('hujra23', 'Давлатов Хафизулло'), ('hujra24', 'Хамидов Аёмчон'), ('hujra25', 'Олимшоев Зафар'), ('hujra26', 'Мухаммадов Сухрод'), ('hujra27', 'Абдулхаков Шамсулло'), ('hujra28', 'Вохидов Сухроб'), ('hujra29', 'Мирзоева Б'), ('hujra30', 'Бобоев Анвар'), ('hujra31', 'Изхоки Сино'), ('hujra32', 'Каноатова Санавбар'), ('hujra33', 'Мирзоев Амирхуча'), ('hujra34', 'Каримов Мачид'), ('hujra35', 'Чураева Насиба '), ('hujra36', 'Рахматуллозода Бахтулло'), ('hujra37', 'Комилзода Илхом'), ('hujra38', 'Ширинзода Эрач'), ('hujra39', 'Ализода Шодмон'), ('hujra40', 'Сангинзода Гайрат '), ('hujra41', 'Мехмондустов Бобчон'), ('hujra42', 'Халифаева Кумринисо'), ('hujra43', 'Саидова Мадина'), ('hujra44', 'Исмоилова Зебо'), ('hujra45', 'Азизи Чалолиддин'), ('hujra46', 'Факиров Файзулло'), ('hujra47', 'Начиббуллоев А.'), ('hujra48', 'Комилов А.'), ('hujra49', 'Махмадёрова Г.'), ('hujra50', 'Расулов Ф.'), ('hujra51', 'Матробиён С.'), ('hujra52', 'Азимова М.'), ('hujra53', 'Муродова Д.'), ('hujra54', 'Рахимзода Ш'), ('hujra55', 'Махмадализода А.'), ('hujra56', 'Абжуллоева С.'), ('hujra57', 'Шокирзода М.'), ('hujra58', 'Салихова М'), ('hujra59', 'Ахмедов С.'), ('hujra60', 'Мубораккадамова Н.'), ('hujra61', 'Бурхонов Д.'), ('hujra62', 'Солихова Х'), ('hujra63', 'Ахмадчонов В.'), ('hujra64', 'Асроров Р.'), ('hujra65', 'Саидова З.'), ('hujra66', 'Чураева М.'), ('hujra67', 'Куронов А.'), ('hujra68', 'Ализда Л.'), ('hujra69', 'Мухиддинов Х.'), ('hujra70', 'Абжуллоев Р.'), ('hujra71', 'Махмадуллоев З.'), ('hujra72', ' Аюбзода Э. ')], max_length=40)),
                ('etaj', models.IntegerField()),
                ('hujra', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pardoxt', models.IntegerField()),
                ('month', models.CharField(choices=[('January', 'Январь'), ('February', 'Февраль'), ('March', 'Март'), ('April', 'Апрель'), ('May', 'Май'), ('June', 'Июнь'), ('July', 'Июль'), ('August', 'Август'), ('September', 'Сентябрь'), ('October', 'Октябрь'), ('November', 'Ноябрь'), ('December', 'Декабрь')], default='Номуайян', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(choices=[('22', '2022'), ('23', '2023'), ('24', '2024'), ('25', '2025'), ('26', '2026')], default=2022, max_length=3)),
                ('spisok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.table')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платёжи',
            },
        ),
    ]
